version: 2
jobs:
  build:
    docker:
      - image: hchauvin/spark-r-ci
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: Format check
          command: ./make.py format_check
      - run:
          name: Test
          command: ./make.py test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"